version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: slackapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d slackapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  init-db:
    build: .
    command: python init_db.py
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/slackapp
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/slackapp
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    depends_on:
      init-db:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
